use chrono::{DateTime, Utc};
use mongodb::{
    Database,
    bson::{DateTime as BsonDateTime, oid::ObjectId},
};

use crate::ai::client::{AiProvider, GeminiClient};
use crate::ai::models::{
    AiConversation, AiConversationResponse, ChatMessage, ChatMessageResponse, ChatRole,
    SendChatMessageResponse, TicketAnalysisResponse, TicketSummaryResponse,
};
use crate::ai::repository::AiRepository;
use crate::config::Config;
use crate::errors::ApiError;
use crate::rbac::service::RbacService;
use crate::ticket::repository::TicketRepository;
use crate::user::service::UserService;

// Confirmed with user: 10 messages per hour, scoped per user (see
// AiRepository::count_recent_user_messages) rather than per ticket — a
// guardrail against one person hammering the endpoint, not a
// per-conversation quota.
const CHAT_RATE_LIMIT: u64 = 10;
const CHAT_RATE_WINDOW_MILLIS: i64 = 60 * 60 * 1000;
// How many prior messages get fed back to Gemini as context on each turn.
// Bounds prompt size/cost regardless of how long a conversation has run —
// the full history still lists in the API response either way, this only
// caps what the model sees.
const CHAT_HISTORY_LIMIT: usize = 20;
// A conversation's title is derived from its first message, not generated by
// Gemini — no reason to spend a call just to name a conversation. This caps
// how much of that first message gets copied into the title.
const TITLE_MAX_CHARS: usize = 60;

// Generic over the provider (default GeminiClient) rather than a concrete
// GeminiClient field: production call sites (AiService::new) are unaffected
// by the default type parameter, while tests can build an
// AiService<FakeProvider> via with_provider to exercise the cache/RBAC logic
// below without ever touching the network — same reasoning as AiProvider's
// doc comment on why it exists at all.
pub struct AiService<P: AiProvider = GeminiClient> {
    repo: AiRepository,
    ticket_repo: TicketRepository,
    user_service: UserService,
    rbac: RbacService,
    provider: P,
}

impl AiService<GeminiClient> {
    // Fails per-request rather than at startup — see Config::gemini_api_key's
    // doc comment on why a missing key doesn't block the whole backend from
    // booting.
    pub fn new(db: &Database, config: &Config) -> Result<Self, ApiError> {
        let api_key = config.gemini_api_key.clone().ok_or_else(|| {
            // Without this line an unset GEMINI_API_KEY is indistinguishable
            // from an upstream provider failure: both are a bare 500 with an
            // "internal_error" body.
            log::error!("GEMINI_API_KEY is not set — AI endpoints will fail");
            ApiError::Internal
        })?;
        Ok(Self::with_provider(db, GeminiClient::new(api_key)))
    }
}

impl<P: AiProvider> AiService<P> {
    pub fn with_provider(db: &Database, provider: P) -> Self {
        Self {
            repo: AiRepository::new(db),
            ticket_repo: TicketRepository::new(db),
            user_service: UserService::new(db),
            rbac: RbacService::new(db),
            provider,
        }
    }

    // docs/api.md: "POST /ai/groups/{id}/tickets/{ticket_id}/summarize —
    // Group-scoped (member of {id} required)".
    pub async fn summarize_ticket(
        &self,
        user_id: ObjectId,
        group_id: ObjectId,
        ticket_id: ObjectId,
    ) -> Result<TicketSummaryResponse, ApiError> {
        self.rbac.require_member(group_id, user_id).await?;
        let ticket = self
            .ticket_repo
            .find_by_id(group_id, ticket_id)
            .await?
            .ok_or(ApiError::NotFound)?;

        let cached = self.repo.find_insight(group_id, ticket_id).await?;
        if let Some(insight) = &cached
            && insight.is_summary_fresh(ticket.content_updated_at)
        {
            return Ok(TicketSummaryResponse {
                summary: insight
                    .summary
                    .clone()
                    .expect("is_summary_fresh implies Some"),
                cached: true,
            });
        }

        let summary = self
            .provider
            .summarize(&ticket.title, &ticket.description)
            .await?;
        self.repo
            .upsert_summary(group_id, ticket_id, &summary, ticket.content_updated_at)
            .await?;
        Ok(TicketSummaryResponse {
            summary,
            cached: false,
        })
    }

    // docs/api.md: "POST /ai/groups/{id}/tickets/{ticket_id}/analyze —
    // Group-scoped (member of {id} required)".
    pub async fn analyze_ticket(
        &self,
        user_id: ObjectId,
        group_id: ObjectId,
        ticket_id: ObjectId,
    ) -> Result<TicketAnalysisResponse, ApiError> {
        self.rbac.require_member(group_id, user_id).await?;
        let ticket = self
            .ticket_repo
            .find_by_id(group_id, ticket_id)
            .await?
            .ok_or(ApiError::NotFound)?;

        let cached = self.repo.find_insight(group_id, ticket_id).await?;
        if let Some(insight) = &cached
            && insight.is_analysis_fresh(ticket.content_updated_at)
        {
            return Ok(TicketAnalysisResponse {
                severity_prediction: insight
                    .severity_prediction
                    .clone()
                    .expect("is_analysis_fresh implies Some"),
                suggested_fix: insight
                    .suggested_fix
                    .clone()
                    .expect("is_analysis_fresh implies Some"),
                classification: insight
                    .classification
                    .clone()
                    .expect("is_analysis_fresh implies Some"),
                cached: true,
            });
        }

        let analysis = self
            .provider
            .analyze(&ticket.title, &ticket.description)
            .await?;
        self.repo
            .upsert_analysis(
                group_id,
                ticket_id,
                &analysis.severity_prediction,
                &analysis.suggested_fix,
                &analysis.classification,
                ticket.content_updated_at,
            )
            .await?;
        Ok(TicketAnalysisResponse {
            severity_prediction: analysis.severity_prediction,
            suggested_fix: analysis.suggested_fix,
            classification: analysis.classification,
            cached: false,
        })
    }

    // Any group member may start a conversation on a ticket, same membership
    // gate as summarize/analyze — but unlike those, a conversation is owned
    // by whoever created it (see require_own_conversation below): no other
    // member, not even a Group Admin, can list, read, or delete it. That's a
    // deliberate departure from comment/the old shared chat, both of which
    // are group-visible.
    pub async fn create_conversation(
        &self,
        user_id: ObjectId,
        group_id: ObjectId,
        ticket_id: ObjectId,
    ) -> Result<AiConversationResponse, ApiError> {
        self.rbac.require_member(group_id, user_id).await?;
        self.ticket_repo
            .find_by_id(group_id, ticket_id)
            .await?
            .ok_or(ApiError::NotFound)?;
        let conversation = self
            .repo
            .create_conversation(group_id, ticket_id, user_id)
            .await?;
        Ok(to_conversation_response(conversation))
    }

    // Only the caller's own conversations — ownership is enforced by the
    // repo query itself (AiRepository::list_conversations filters on
    // user_id), not a per-item check here. Most-recently-active first.
    pub async fn list_conversations(
        &self,
        user_id: ObjectId,
        group_id: ObjectId,
        ticket_id: ObjectId,
    ) -> Result<Vec<AiConversationResponse>, ApiError> {
        self.rbac.require_member(group_id, user_id).await?;
        self.ticket_repo
            .find_by_id(group_id, ticket_id)
            .await?
            .ok_or(ApiError::NotFound)?;
        let conversations = self
            .repo
            .list_conversations(group_id, ticket_id, user_id)
            .await?;
        Ok(conversations
            .into_iter()
            .map(to_conversation_response)
            .collect())
    }

    // Fetches a conversation and checks it both belongs to this ticket (a
    // conversation_id from another ticket/group in the URL is NotFound, same
    // as TicketRepository::find_by_id treating a wrong group_id as "doesn't
    // exist" rather than leaking that it belongs to someone else) and is
    // owned by the caller (a real ownership mismatch is Forbidden — there's
    // no owner-or-group-admin fallback for conversations, unlike
    // RbacService::require_owner_or_group_admin's use in comment deletion).
    async fn require_own_conversation(
        &self,
        user_id: ObjectId,
        group_id: ObjectId,
        ticket_id: ObjectId,
        conversation_id: ObjectId,
    ) -> Result<AiConversation, ApiError> {
        let conversation = self
            .repo
            .find_conversation(conversation_id)
            .await?
            .ok_or(ApiError::NotFound)?;
        if conversation.group_id != group_id || conversation.ticket_id != ticket_id {
            return Err(ApiError::NotFound);
        }
        if conversation.user_id != user_id {
            return Err(ApiError::Forbidden);
        }
        Ok(conversation)
    }

    // Unlike summarize/analyze, this is never cacheable: each message is a
    // genuinely new request, there's no "fresh iff unchanged" check to make.
    // Message format validation (empty/over-length) lives in the handler
    // only, same as comment content — see comment_handlers::validate_create's
    // doc comment for why the split is there and not duplicated here.
    pub async fn send_conversation_message(
        &self,
        user_id: ObjectId,
        group_id: ObjectId,
        ticket_id: ObjectId,
        conversation_id: ObjectId,
        message: String,
    ) -> Result<SendChatMessageResponse, ApiError> {
        self.rbac.require_member(group_id, user_id).await?;
        let ticket = self
            .ticket_repo
            .find_by_id(group_id, ticket_id)
            .await?
            .ok_or(ApiError::NotFound)?;
        self.require_own_conversation(user_id, group_id, ticket_id, conversation_id)
            .await?;

        let since = BsonDateTime::from_millis(
            BsonDateTime::now().timestamp_millis() - CHAT_RATE_WINDOW_MILLIS,
        );
        let recent_count = self.repo.count_recent_user_messages(user_id, since).await?;
        if recent_count >= CHAT_RATE_LIMIT {
            return Err(ApiError::RateLimited(format!(
                "chat message limit reached ({CHAT_RATE_LIMIT} per hour) — try again later"
            )));
        }

        let history = self.repo.list_conversation_messages(conversation_id).await?;
        let transcript = build_transcript(&history);
        let reply = self
            .provider
            .chat(&ticket.title, &ticket.description, &transcript, &message)
            .await?;

        let user_message = self
            .repo
            .insert_chat_message(
                conversation_id,
                group_id,
                ticket_id,
                ChatRole::User,
                Some(user_id),
                &message,
            )
            .await?;
        let assistant_message = self
            .repo
            .insert_chat_message(
                conversation_id,
                group_id,
                ticket_id,
                ChatRole::Assistant,
                None,
                &reply,
            )
            .await?;
        self.repo
            .touch_conversation(conversation_id, &derive_title(&message))
            .await?;

        Ok(SendChatMessageResponse {
            user_message: self.enrich_chat_message(user_message).await?,
            assistant_message: self.enrich_chat_message(assistant_message).await?,
        })
    }

    // Whole conversation, oldest-first, no pagination — same shape and
    // reasoning as CommentService::list_comments.
    pub async fn list_conversation_messages(
        &self,
        user_id: ObjectId,
        group_id: ObjectId,
        ticket_id: ObjectId,
        conversation_id: ObjectId,
    ) -> Result<Vec<ChatMessageResponse>, ApiError> {
        self.rbac.require_member(group_id, user_id).await?;
        self.require_own_conversation(user_id, group_id, ticket_id, conversation_id)
            .await?;
        let messages = self.repo.list_conversation_messages(conversation_id).await?;
        let mut result = Vec::with_capacity(messages.len());
        for message in messages {
            result.push(self.enrich_chat_message(message).await?);
        }
        Ok(result)
    }

    // Deletes one of the caller's own conversations — strictly owner-only,
    // see require_own_conversation.
    pub async fn delete_conversation(
        &self,
        user_id: ObjectId,
        group_id: ObjectId,
        ticket_id: ObjectId,
        conversation_id: ObjectId,
    ) -> Result<(), ApiError> {
        self.rbac.require_member(group_id, user_id).await?;
        self.require_own_conversation(user_id, group_id, ticket_id, conversation_id)
            .await?;
        self.repo.delete_conversation(conversation_id).await?;
        Ok(())
    }

    // ChatMessageResponse needs the author's display name, which ChatMessage
    // doesn't carry — mirrors CommentService::enrich_comment. None for an
    // assistant message (no user_id to look up).
    async fn enrich_chat_message(
        &self,
        message: ChatMessage,
    ) -> Result<ChatMessageResponse, ApiError> {
        let user_name = match message.user_id {
            Some(uid) => self.user_service.find_by_id(uid).await?.map(|u| u.name),
            None => None,
        };
        Ok(ChatMessageResponse {
            id: message.id.map(|id| id.to_hex()).unwrap_or_default(),
            role: message.role,
            user_id: message.user_id.map(|id| id.to_hex()),
            user_name,
            content: message.content,
            created_at: to_chrono(message.created_at),
        })
    }
}

// Last CHAT_HISTORY_LIMIT messages, oldest-first, rendered as plain text for
// the prompt — kept as a free function so it's unit-testable without a
// provider or DB (same reasoning as aggregate_stats/stats_summary below).
fn build_transcript(history: &[ChatMessage]) -> String {
    let start = history.len().saturating_sub(CHAT_HISTORY_LIMIT);
    history[start..]
        .iter()
        .map(|message| {
            let speaker = match message.role {
                ChatRole::User => "User",
                ChatRole::Assistant => "Assistant",
            };
            format!("{speaker}: {}", message.content)
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn to_chrono(ts: BsonDateTime) -> DateTime<Utc> {
    DateTime::from_timestamp_millis(ts.timestamp_millis()).unwrap_or_default()
}

fn to_conversation_response(conversation: AiConversation) -> AiConversationResponse {
    AiConversationResponse {
        id: conversation.id.map(|id| id.to_hex()).unwrap_or_default(),
        title: conversation.title,
        created_at: to_chrono(conversation.created_at),
        updated_at: to_chrono(conversation.updated_at),
    }
}

// Truncates on a char boundary (not byte) — same reasoning as
// comment_handlers::validate_create counting .chars() rather than .len(), so
// a multi-byte character never gets split mid-codepoint.
fn derive_title(content: &str) -> String {
    let trimmed = content.trim();
    if trimmed.chars().count() <= TITLE_MAX_CHARS {
        trimmed.to_string()
    } else {
        let truncated: String = trimmed.chars().take(TITLE_MAX_CHARS).collect();
        format!("{truncated}…")
    }
}
